### ISSUE TITLE
[BUG]: Relative Absolute Error

### ISSUE THREAD

**Issue by 321HG** [thieu1995/permetrics#6]
### Description of the bug

Is there an error in the formula of Relative Absolute Error?

### Steps To Reproduce

![20240314192734](https://github.com/thieu1995/permetrics/assets/54180767/df276f83-cf88-4cc2-aa7e-be969903319e)

**Comment by thieu1995** [comment]
Hi @321HG ,

I follow this metric from here: https://www.statisticshowto.com/relative-absolute-error/
There is an article for that metric. You can check it out. I have the same thought as you when I read about the name and the equation.

**Comment by 321HG** [comment]
Thank you for your correction, I really appreciate it!
